name: Build Artifact
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact
        run: echo 'Test Artifact' > artifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: artifact.txt