name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > artifact.txt
      - uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: artifact.txt